### ISSUE TITLE
трудно читаемый код

### ISSUE THREAD

**Issue by pinkyfox** [twinpixxx/restful-application#1]
https://github.com/twinpixxx/restful-application/blob/c0a76bf31eb06ebd4378f14b5be111240ac19c6a/src/main/java/com/labs/restservice/calculations/CalculationService.java#L18

**Comment by twinpixxx** [comment]
Ok, got it. This issue will be resolved ASAP. 
Any suggestions on how to refactor this?
cc @pinkyfox
